Lab.TPAPI.UI/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Lab.TPAPI.UI.Areas.HelpPage.ModelDescriptions;
using Lab.TPAPI.UI.Areas.HelpPage.Models;

namespace Lab.TPAPI.UI.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Lab.TPAPI.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.TPAPI.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

Lab.TPAPI.UI/Controllers/SunInformationController.cs
using Lab.TPAPI.UI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.TPAPI.UI.Controllers
{
    public class SunInformationController : Controller
    {
        private static HttpClient ApiClient { get; set; }

        public SunInformationController()
        {
            InitializeClient();
        }

        private static void InitializeClient()
        {
            if (ApiClient == null)
            {
                ApiClient = new HttpClient();
                ApiClient.DefaultRequestHeaders.Accept.Clear();
                ApiClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
            }
        }

        // GET: SunInformation
        public async Task<ActionResult> Index()
        {
            string url = "https://api.sunrise-sunset.org/json?lat=-38.00042&lng=-57.5562&date=today";

            var json = await ApiClient.GetStringAsync(url);

            SunResultModel result = JsonConvert.DeserializeObject<SunResultModel>(json);

            SunModel sunModel = new SunModel
            {
                Sunrise = result.Results.Sunrise.ToLocalTime(),
                Sunset = result.Results.Sunset.ToLocalTime()
            };

            return View(sunModel);
        }
    }
}

Lab.TPAPI.UI/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>My Web API Application</h1>
    <p class="lead">This is a proyect with ASP.NET Web API. It can modify Order Details from the Northwind test database, and ask for Sunrise and Sunset details from the sunrise-sunset.org API.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more about ASP.NET &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>API Documentation</h2>
        <p>Click the link below, or click on "API" in the Navbar above to learn more
        about my API.</p>
        <button class="btn btn-default">
            @Html.ActionLink("API >>", "Index", "Help", new { area = "" }, null)
        </button>
    </div>
    <div class="col-md-4">
        <h2>Inventory</h2>
        <p>Manage the Items saved in the Orders on the Northwind Database. Click the link below, or "Inventory" in the Navbar.</p>
        <button class="btn btn-default">
            @Html.ActionLink("Inventory >>", "Index", "Inventory", new { area = "" }, null)
        </button>
    </div>
    <div class="col-md-4">
        <h2>Sunrise Information</h2>
        <p>Consult the sunrise-sunset.org API about Sunrise information on Mar del Plata.
        Click the link below, or "Sun Information" in the navbar.</p>
        <button class="btn btn-default">
            @Html.ActionLink("Sun Information >>", "Index", "SunInformation", new { area = "" }, null)
        </button>
    </div>
</div>